Add display headings
transferwise/bootstrap pull request #100
Opened 2017-05-04 14:53 UTC by kdelemme

2017-05-04 16:55 UTC, StevePole requested changes

2017-05-04 16:55 UTC, StevePole commented on dist/css/bootstrap.css
> +  font-size: 6rem;
Bootstrap 4 uses rem but we don't, we should map these to pixel size.  Would suggest talking with Julian to come up with sizes.

2017-05-04 16:55 UTC, StevePole commented on dist/css/bootstrap.css
> +  font-size: 6rem;
All our line-heights should be a multiple of 8px, although font-size can be anything.

2017-05-04 16:55 UTC, StevePole commented on less/variables.less
> +@display4-weight:     300;
Talk to Julian about font-weight, I suspect we will match our existing headings.

2017-05-05 08:25 UTC, kdelemme commented on dist/css/bootstrap.css
> +  font-size: 6rem;
Thanks will talk with him

2017-05-05 09:45 UTC, StevePole commented
Another thought, we use responsive typography.  So for all of our headings, they drop down to the next smallest size on mobile, the change happens at this breakpoint in type.less

@media (min-width: @screen-md-min) {

Could you add this?

2017-05-05 09:45 UTC, StevePole commented on dist/css/bootstrap.css
> +  line-height: 56px;
Line-height + margin should also be multiple of 8 if possible

2017-05-05 14:03 UTC, StevePole approved these changes

2017-05-05 14:38 UTC, merged