Jumbotron bg-focus updates
transferwise/bootstrap pull request #112
Opened 2017-07-31 09:09 UTC by coolsebz

Changes:
- jumbotron now supports bg-focus as a contextual background

Visual demo:
![screen shot 2017-07-30 at 22 47 25](https://user-images.githubusercontent.com/2954356/28770788-57ddd374-75d8-11e7-80c6-640dbfe8a12a.png)

2017-08-01 08:58 UTC, StevePole commented on less/jumbotron.less
> +  }
Don't think we need these two any more?

2017-08-01 12:08 UTC, coolsebz commented on less/jumbotron.less
> +  }
mmh not sure, i've added .bg focus as a way to keep the default jumbotron to it's current styles but just enforce a white bg

happy to move the default jumbotron styles to this then (plus migrate old styles onto navy bg + white font)

2017-08-01 12:10 UTC, coolsebz commented on less/type.less
>    color: @brand-smoke-plus-20;
@StevePole in between this line and :374, which one do we actually use (i'd want to remove the one that is outdated if possible)

2017-08-01 14:17 UTC, StevePole commented on less/jumbotron.less
> +  }
I think these are the default colours for these things anyway.  The only reason for having them is to overule the jumbotron styles, but over-ruling back to what they would have been anyway sucks.  That's why I was thinking we could move those text colours onto `.jumbotron-image` and `.hero-with-background` so we no longer have styles on jumbotron by default.

2017-08-01 14:18 UTC, StevePole commented on less/type.less
>    color: @brand-smoke-plus-20;
374 looks incorrect.  We don't use the wash colour for bg-primary.

2017-08-04 08:37 UTC, StevePole requested changes

2017-08-04 08:37 UTC, StevePole commented on less/jumbotron.less
> +  &.bg-primary, &.bg-info, .jumbotron-image & {
I don't think it's necessary to have bg-primary and bg-info here anymore.  Thos classes should change heading colours etc already.

2017-08-04 11:26 UTC, coolsebz commented on less/jumbotron.less
> +  &.bg-primary, &.bg-info, .jumbotron-image & {
cool, i'll remove it and test 👍 
edit: leaving jumbotron-image in there, that one's actually needed to "simulate" bg-primary

2017-08-04 11:48 UTC, StevePole approved these changes
LGTM

2017-08-04 12:53 UTC, merged